### ISSUE TITLE
bubbo bubbo GSAP and License

### ISSUE THREAD

**Issue by aJamDonut** [pixijs/open-games#2]
The new project examples are great to start up new projects although I do think it should be made clear of all packages and licenses within the project examples. GSAP is not MIT licenced and is used in bubbo bubbo - this should therefore be expressly stated on bubbo bubbo readme.

**Comment by Zyie** [comment]
Hey!

Thanks for bringing this to my attention. I have added a section for gsap for both projects readme's with info on gsaps licensing
