### ISSUE TITLE
Cannot find ffmpeg

### ISSUE THREAD

**Issue by d1sna** [pixijs/open-games#4]
I've got problem on my local machine while runnig each of both repositories, i have nvm and tried to use 16.17.1 and 18.12.1

<img width="359" alt="Снимок экрана 2023-09-08 в 11 36 31" src="https://github.com/pixijs/open-games/assets/56303300/3e619d78-767d-4e52-bd71-c7444ac7686b">

**Comment by mikle7** [comment]
Same issue here

**Comment by mikle7** [comment]
@d1sna Upgrade your asset packs in package.json to the latest 0.7.0 and it works again. 


`        "@assetpack/cli": "^0.7.0",
        "@assetpack/core": "^0.7.0",
        "@assetpack/plugin-compress": "^0.7.0",
        "@assetpack/plugin-ffmpeg": "^0.7.0",
        "@assetpack/plugin-json": "^0.7.0",
        "@assetpack/plugin-manifest": "^0.7.0",
        "@assetpack/plugin-mipmap": "^0.7.0",
        "@assetpack/plugin-texture-packer": "^0.7.0",
        "@assetpack/plugin-webfont": "^0.7.0",`

**Comment by d1sna** [comment]
Thank you! 
it works with bubbo-bubbo, "puzzling" gets white screen after running :)

**Comment by d1sna** [comment]
> @d1sna Upgrade your asset packs in package.json to the latest 0.7.0 and it works again.
> 
> ` "@assetpack/cli": "^0.7.0", "@assetpack/core": "^0.7.0", "@assetpack/plugin-compress": "^0.7.0", "@assetpack/plugin-ffmpeg": "^0.7.0", "@assetpack/plugin-json": "^0.7.0", "@assetpack/plugin-manifest": "^0.7.0", "@assetpack/plugin-mipmap": "^0.7.0", "@assetpack/plugin-texture-packer": "^0.7.0", "@assetpack/plugin-webfont": "^0.7.0",`
> 
> #5

Thank you!
it works with bubbo-bubbo, "puzzling" gets white screen after running :)

**Comment by hughdtt** [comment]
@d1sna for puzzle game, you can update pixi.js to v7.2.4 in package.json.

**Comment by bigtimebuddy** [comment]
assetpack has been bumped, closing issue. Let us know if this is still an issue and can re-open.
